"""empty message

Revision ID: 46fa0b55791e
Revises: 77cb8fe270cd
Create Date: 2024-08-25 22:15:26.929398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46fa0b55791e'
down_revision: Union[str, None] = '77cb8fe270cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('documents_text_id_doc_fkey', 'documents_text', type_='foreignkey')
    op.create_foreign_key(None, 'documents_text', 'documents', ['id_doc'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents_text', type_='foreignkey')
    op.create_foreign_key('documents_text_id_doc_fkey', 'documents_text', 'documents', ['id_doc'], ['id'])
    # ### end Alembic commands ###
